# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import identifier_pb2 as identifier__pb2


class IdentifiersStub(object):
    """Defining the service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentifiers = channel.unary_unary(
                '/Identifiers/GetIdentifiers',
                request_serializer=identifier__pb2.IdentifierRequest.SerializeToString,
                response_deserializer=identifier__pb2.IdentifierResponse.FromString,
                )


class IdentifiersServicer(object):
    """Defining the service 
    """

    def GetIdentifiers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentifiersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentifiers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentifiers,
                    request_deserializer=identifier__pb2.IdentifierRequest.FromString,
                    response_serializer=identifier__pb2.IdentifierResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Identifiers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Identifiers(object):
    """Defining the service 
    """

    @staticmethod
    def GetIdentifiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Identifiers/GetIdentifiers',
            identifier__pb2.IdentifierRequest.SerializeToString,
            identifier__pb2.IdentifierResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
