# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identifier.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10identifier.proto\"A\n\x11IdentifierRequest\x12,\n\x11identifier_option\x18\x01 \x01(\x0e\x32\x11.IdentifierOption\" \n\nIdentifier\x12\x12\n\nidentifier\x18\x01 \x01(\t\"6\n\x12IdentifierResponse\x12 \n\x0bidentifiers\x18\x01 \x03(\x0b\x32\x0b.Identifier*%\n\x10IdentifierOption\x12\x08\n\x04\x43USA\x10\x00\x12\x07\n\x03URL\x10\x01\x32H\n\x0bIdentifiers\x12\x39\n\x0eGetIdentifiers\x12\x12.IdentifierRequest\x1a\x13.IdentifierResponseb\x06proto3'
)

_IDENTIFIEROPTION = _descriptor.EnumDescriptor(
  name='IdentifierOption',
  full_name='IdentifierOption',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUSA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='URL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=177,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_IDENTIFIEROPTION)

IdentifierOption = enum_type_wrapper.EnumTypeWrapper(_IDENTIFIEROPTION)
CUSA = 0
URL = 1



_IDENTIFIERREQUEST = _descriptor.Descriptor(
  name='IdentifierRequest',
  full_name='IdentifierRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier_option', full_name='IdentifierRequest.identifier_option', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=85,
)


_IDENTIFIER = _descriptor.Descriptor(
  name='Identifier',
  full_name='Identifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='Identifier.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=119,
)


_IDENTIFIERRESPONSE = _descriptor.Descriptor(
  name='IdentifierResponse',
  full_name='IdentifierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifiers', full_name='IdentifierResponse.identifiers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=175,
)

_IDENTIFIERREQUEST.fields_by_name['identifier_option'].enum_type = _IDENTIFIEROPTION
_IDENTIFIERRESPONSE.fields_by_name['identifiers'].message_type = _IDENTIFIER
DESCRIPTOR.message_types_by_name['IdentifierRequest'] = _IDENTIFIERREQUEST
DESCRIPTOR.message_types_by_name['Identifier'] = _IDENTIFIER
DESCRIPTOR.message_types_by_name['IdentifierResponse'] = _IDENTIFIERRESPONSE
DESCRIPTOR.enum_types_by_name['IdentifierOption'] = _IDENTIFIEROPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentifierRequest = _reflection.GeneratedProtocolMessageType('IdentifierRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIERREQUEST,
  '__module__' : 'identifier_pb2'
  # @@protoc_insertion_point(class_scope:IdentifierRequest)
  })
_sym_db.RegisterMessage(IdentifierRequest)

Identifier = _reflection.GeneratedProtocolMessageType('Identifier', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIER,
  '__module__' : 'identifier_pb2'
  # @@protoc_insertion_point(class_scope:Identifier)
  })
_sym_db.RegisterMessage(Identifier)

IdentifierResponse = _reflection.GeneratedProtocolMessageType('IdentifierResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIERRESPONSE,
  '__module__' : 'identifier_pb2'
  # @@protoc_insertion_point(class_scope:IdentifierResponse)
  })
_sym_db.RegisterMessage(IdentifierResponse)



_IDENTIFIERS = _descriptor.ServiceDescriptor(
  name='Identifiers',
  full_name='Identifiers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=216,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetIdentifiers',
    full_name='Identifiers.GetIdentifiers',
    index=0,
    containing_service=None,
    input_type=_IDENTIFIERREQUEST,
    output_type=_IDENTIFIERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IDENTIFIERS)

DESCRIPTOR.services_by_name['Identifiers'] = _IDENTIFIERS

# @@protoc_insertion_point(module_scope)
